### @baseUrl = http://localhost:3030
@baseUrl = https://frozen-headland-66513.herokuapp.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTU2YzA4YjAwZmRjNWQ3NGZiMGNkMmQiLCJlbWFpbCI6ImJhZEBkb2UuY29tIiwiaWF0IjoxNjMzMDc1MzQzLCJleHAiOjE2MzM2ODAxNDN9.ChAXldZ7AlMHtkbK6bl3GqjQDsjzTV1v6Vz3U6nrKMA


###             ###
### CREATE USER ###
###             ###
POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "bad@doe.com",
    "firstName": "Bad",
    "lastName": "Doe",
    "password": "password123"
}

### LOGIN WITH USER
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "bad@doe.com",
    "password": "password123"
}


###                     ###
### CREATE A CABIN POST ###
###                     ###
POST {{baseUrl}}/cabins
Content-Type: application/json
Authorization: Barer {{token}}

{
    "address": "Testikuja 47",
    "size": 24,
    "sauna": true,
    "beach": true,
    "rent": 507
}

### SEE ALL CABIN POSTS
GET {{baseUrl}}/cabins
Authorization: Barer {{token}}

### SEE A SPECIFIC CABIN POST
GET {{baseUrl}}/cabins/6152e0cae1bb134fad7587a1
Authorization: Barer {{token}}

### EDIT INFO OF A CABIN POST
PUT {{baseUrl}}/cabins/6152e0cae1bb134fad7587a1
Content-Type: application/json
Authorization: Barer {{token}}

{
    "address": "Kalliokuja",
    "size": 24,
    "sauna": true,
    "beach": false,
    "rent": 499
}

### DELETE A SPECIFIC CABIN POST
DELETE {{baseUrl}}/cabins/6152e0cae1bb134fad7587a1
Authorization: Barer {{token}}


###                    ###
### SEE & DELETE USERS ###
###                    ###

### SEE ALL USERS
GET {{baseUrl}}/users
Content-Type: application/json

### DELETE A SPECIFIC USER
DELETE {{baseUrl}}/users/61519d9cdd5d6e645477d282