@baseUrl = http://localhost:3030
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTUxOWJhMzc3ZTViNDhjY2M0NzYzMDAiLCJlbWFpbCI6InNlYkBkb2UuY29tIiwiaWF0IjoxNjMyNzM5MDcwLCJleHAiOjE2MzI4MjU0NzB9.x_8XqJaUdcAeUmV96MxQK9VswuZqrwjhFDVR8BVOV_k

### Login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "jane@doe.com",
    "password": "pwd123"
}

### Create user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "jane@doe.com",
    "firstName": "Jane",
    "lastName": "Doe",
    "password": "pwd123"
}

### GET all users
GET {{baseUrl}}/users
Content-Type: application/json

### DELETE user
DELETE {{baseUrl}}/users/<id>
Authorization: Barer {{token}}